version: "3.9" # yamlのバージョン。
services:
  python:
    build:
      context: ./docker/python/python
      dockerfile: ./docker/python/Dockerfile

    # Jupyter Labのentrypointの設定
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0  
      --port=8888
      --no-browser
      --NotebookApp.token="" 
      --notebook-dir= ./モデル作成:/app/モデル作成

    #解放するポートの設定
    # コンテナ内で8888番ポートを公開
    # ホストのポート8888をコンテナのポート8888にマッピング
    # ホストマシンのみアクセス許可
    expose:
      - "8888"
    ports:
      - "127.0.0.1:8000:8000"
    # マウントの設定  
    volumes:
      - ./data:/app/data
      - ./scrape用:/app/scrape用
      - ./データ整形用:/app/データ整形用
      - ./モデル作成:/app/モデル作成
      - ./分析用:/app/分析用
    
      
    tty: true
    